module.exports.useMasterKey = { useMasterKey: true }
module.exports.User = Parse.Object.extend('User');
module.exports.Project = Parse.Object.extend('Project');
module.exports.Category = Parse.Object.extend('Category');
module.exports.Vote = Parse.Object.extend('Vote');
module.exports.Queue = Parse.Object.extend('Queue');
module.exports.JudgingCriteria = Parse.Object.extend('JudgingCriteria');
module.exports.JudgeToCategory = Parse.Object.extend('JudgeToCategory');
module.exports.Global = Parse.Object.extend('Global');